2025-01-17 12:42:38,552 INFO: Application startup in development mode [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\__init__.py:84]
2025-01-17 12:42:38,552 INFO: Running with BASE_DIR: c:\Users\BJ.Marshall\Documents\python\REI-Tracker [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\__init__.py:101]
2025-01-17 12:42:38,554 INFO: Environment: Development [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\__init__.py:102]
2025-01-17 12:42:38,851 INFO: All Dash apps initialized successfully [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\__init__.py:176]
2025-01-17 12:42:39,539 INFO: Application startup in development mode [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\__init__.py:84]
2025-01-17 12:42:39,540 INFO: Running with BASE_DIR: c:\Users\BJ.Marshall\Documents\python\REI-Tracker [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\__init__.py:101]
2025-01-17 12:42:39,541 INFO: Environment: Development [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\__init__.py:102]
2025-01-17 12:42:39,814 INFO: All Dash apps initialized successfully [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\__init__.py:176]
2025-01-17 12:42:50,845 ERROR: Error processing file: [Errno 9] Bad file descriptor [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\routes\transactions.py:309]
2025-01-17 12:42:50,847 ERROR: Error processing file: [Errno 9] Bad file descriptor [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\routes\transactions.py:309]
2025-01-17 12:46:10,152 ERROR: Error processing file: [Errno 9] Bad file descriptor [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\routes\transactions.py:309]
2025-01-17 12:46:10,153 ERROR: Error processing file: [Errno 9] Bad file descriptor [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\routes\transactions.py:309]
2025-01-17 12:49:29,723 INFO: Application startup in development mode [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\__init__.py:84]
2025-01-17 12:49:29,724 INFO: Running with BASE_DIR: c:\Users\BJ.Marshall\Documents\python\REI-Tracker [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\__init__.py:101]
2025-01-17 12:49:29,725 INFO: Environment: Development [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\__init__.py:102]
2025-01-17 12:49:30,020 INFO: All Dash apps initialized successfully [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\__init__.py:176]
2025-01-17 12:49:57,083 INFO: Application startup in development mode [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\__init__.py:84]
2025-01-17 12:49:57,083 INFO: Running with BASE_DIR: c:\Users\BJ.Marshall\Documents\python\REI-Tracker [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\__init__.py:101]
2025-01-17 12:49:57,084 INFO: Environment: Development [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\__init__.py:102]
2025-01-17 12:49:57,404 INFO: All Dash apps initialized successfully [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\__init__.py:176]
2025-01-17 12:50:26,352 INFO: Successfully added transaction with ID: 65 [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\services\transaction_service.py:64]
2025-01-17 12:50:26,352 INFO: Successfully added transaction with ID: 65 [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\services\transaction_service.py:64]
2025-01-17 12:50:26,373 INFO: Successfully added transaction with ID: 66 [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\services\transaction_service.py:64]
2025-01-17 12:50:26,373 INFO: Successfully added transaction with ID: 66 [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\services\transaction_service.py:64]
2025-01-17 12:50:26,383 INFO: Successfully added transaction with ID: 67 [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\services\transaction_service.py:64]
2025-01-17 12:50:26,384 INFO: Successfully added transaction with ID: 67 [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\services\transaction_service.py:64]
2025-01-17 12:50:26,396 INFO: Successfully added transaction with ID: 68 [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\services\transaction_service.py:64]
2025-01-17 12:50:26,396 INFO: Successfully added transaction with ID: 68 [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\services\transaction_service.py:64]
2025-01-17 12:50:26,417 INFO: Successfully added transaction with ID: 69 [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\services\transaction_service.py:64]
2025-01-17 12:50:26,418 INFO: Successfully added transaction with ID: 69 [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\services\transaction_service.py:64]
2025-01-17 12:50:26,429 INFO: Successfully added transaction with ID: 70 [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\services\transaction_service.py:64]
2025-01-17 12:50:26,429 INFO: Successfully added transaction with ID: 70 [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\services\transaction_service.py:64]
2025-01-17 12:50:28,441 INFO: View transactions accessed by user: {'id': 'bjmar867@gmail.com', 'name': 'BJ Marshall', 'role': 'Admin', 'is_authenticated': True} [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\routes\transactions.py:406]
2025-01-17 12:50:28,454 INFO: View transactions accessed by user: {'id': 'bjmar867@gmail.com', 'name': 'BJ Marshall', 'role': 'Admin', 'is_authenticated': True} [in c:\Users\BJ.Marshall\Documents\python\REI-Tracker\routes\transactions.py:406]
2025-01-19 09:47:59,490 INFO: Application startup in development mode [in /home/bj/python/REI-Tracker/__init__.py:84]
2025-01-19 09:47:59,490 INFO: Running with BASE_DIR: /home/bj/python/REI-Tracker [in /home/bj/python/REI-Tracker/__init__.py:101]
2025-01-19 09:47:59,490 INFO: Environment: Development [in /home/bj/python/REI-Tracker/__init__.py:102]
2025-01-19 09:47:59,551 INFO: All Dash apps initialized successfully [in /home/bj/python/REI-Tracker/__init__.py:176]
2025-01-19 09:48:00,041 INFO: Application startup in development mode [in /home/bj/python/REI-Tracker/__init__.py:84]
2025-01-19 09:48:00,041 INFO: Running with BASE_DIR: /home/bj/python/REI-Tracker [in /home/bj/python/REI-Tracker/__init__.py:101]
2025-01-19 09:48:00,041 INFO: Environment: Development [in /home/bj/python/REI-Tracker/__init__.py:102]
2025-01-19 09:48:00,082 INFO: All Dash apps initialized successfully [in /home/bj/python/REI-Tracker/__init__.py:176]
2025-01-19 10:04:17,467 INFO: Application startup in development mode [in /home/bj/python/REI-Tracker/__init__.py:84]
2025-01-19 10:04:17,467 INFO: Running with BASE_DIR: /home/bj/python/REI-Tracker [in /home/bj/python/REI-Tracker/__init__.py:101]
2025-01-19 10:04:17,467 INFO: Environment: Development [in /home/bj/python/REI-Tracker/__init__.py:102]
2025-01-19 10:04:17,507 INFO: All Dash apps initialized successfully [in /home/bj/python/REI-Tracker/__init__.py:176]
2025-01-19 10:04:18,055 INFO: Application startup in development mode [in /home/bj/python/REI-Tracker/__init__.py:84]
2025-01-19 10:04:18,056 INFO: Running with BASE_DIR: /home/bj/python/REI-Tracker [in /home/bj/python/REI-Tracker/__init__.py:101]
2025-01-19 10:04:18,056 INFO: Environment: Development [in /home/bj/python/REI-Tracker/__init__.py:102]
2025-01-19 10:04:18,095 INFO: All Dash apps initialized successfully [in /home/bj/python/REI-Tracker/__init__.py:176]
2025-01-19 10:04:38,763 INFO: View transactions accessed by user: {'id': 'bjmar867@gmail.com', 'name': 'BJ Marshall', 'role': 'Admin', 'is_authenticated': True} [in /home/bj/python/REI-Tracker/routes/transactions.py:406]
2025-01-19 10:04:56,672 ERROR: File not found: /home/bj/python/REI-Tracker/data/uploads/reimb_2024.11-12_Zelle_Transactions_with_Brian.png [in /home/bj/python/REI-Tracker/routes/transactions.py:432]
2025-01-19 10:04:56,672 ERROR: Error serving artifact reimb_2024.11-12_Zelle_Transactions_with_Brian.png: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in /home/bj/python/REI-Tracker/routes/transactions.py:442]
2025-01-19 10:04:56,673 ERROR: Full error traceback: Traceback (most recent call last):
  File "/home/bj/python/REI-Tracker/routes/transactions.py", line 433, in get_artifact
    abort(404)
  File "/home/bj/python/REI-Tracker/venv/lib/python3.11/site-packages/flask/helpers.py", line 274, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/home/bj/python/REI-Tracker/venv/lib/python3.11/site-packages/werkzeug/exceptions.py", line 861, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
 [in /home/bj/python/REI-Tracker/routes/transactions.py:443]
2025-01-19 10:16:02,470 INFO: Application startup in development mode [in /home/bj/python/REI-Tracker/__init__.py:84]
2025-01-19 10:16:02,470 INFO: Running with BASE_DIR: /home/bj/python/REI-Tracker [in /home/bj/python/REI-Tracker/__init__.py:101]
2025-01-19 10:16:02,471 INFO: Environment: Development [in /home/bj/python/REI-Tracker/__init__.py:102]
2025-01-19 10:16:02,510 INFO: All Dash apps initialized successfully [in /home/bj/python/REI-Tracker/__init__.py:176]
2025-01-19 10:16:45,711 INFO: Application startup in development mode [in /home/bj/python/REI-Tracker/__init__.py:84]
2025-01-19 10:16:45,711 INFO: Running with BASE_DIR: /home/bj/python/REI-Tracker [in /home/bj/python/REI-Tracker/__init__.py:101]
2025-01-19 10:16:45,711 INFO: Environment: Development [in /home/bj/python/REI-Tracker/__init__.py:102]
2025-01-19 10:16:45,749 INFO: All Dash apps initialized successfully [in /home/bj/python/REI-Tracker/__init__.py:176]
2025-01-19 10:30:24,071 INFO: Application startup in development mode [in /home/bj/python/REI-Tracker/__init__.py:84]
2025-01-19 10:30:24,072 INFO: Running with BASE_DIR: /home/bj/python/REI-Tracker [in /home/bj/python/REI-Tracker/__init__.py:101]
2025-01-19 10:30:24,072 INFO: Environment: Development [in /home/bj/python/REI-Tracker/__init__.py:102]
2025-01-19 10:30:24,110 INFO: All Dash apps initialized successfully [in /home/bj/python/REI-Tracker/__init__.py:176]
